name: PandoraKERNEL - GKI Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build PandoraKERNEL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4

      - name: Set up Clang
        uses: rickstaa/action-install-gh-release@v1
        with:
          repo: ClangBuiltLinux/llvm-project
          tag: llvmorg-17.0.6
          files: |
            clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-20.04.tar.xz

      - name: Extract Clang
        run: |
          mkdir clang
          tar -xf clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-20.04.tar.xz -C clang --strip-components=1

      - name: Build PandoraKERNEL
        run: |
          export PATH=$PWD/clang/bin:$PATH
          export CLANG_TRIPLE=aarch64-linux-gnu-
          make O=out ARCH=arm64 gki_defconfig
          make -j$(nproc) O=out ARCH=arm64 \
            CC=clang \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_COMPAT=arm-linux-gnueabi-

      - name: Pack with AnyKernel3
        run: |
          git clone https://github.com/osm0sis/AnyKernel3.git
          cp out/arch/arm64/boot/Image.gz AnyKernel3/
          cd AnyKernel3
          zip -r9 PandoraKERNEL-GKI.zip *

      - name: Upload Kernel Zip
        uses: actions/upload-artifact@v4
        with:
          name: PandoraKERNEL-GKI
          path: AnyKernel3/PandoraKERNEL-GKI.zip