name: Build PandoraKERNEL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Clang
        run: |
          git clone --depth=1 https://github.com/ZyCromerZ/Clang --branch 17-stable ~/clang
          echo "CLANG_PATH=$HOME/clang" >> $GITHUB_ENV

      - name: Build Kernel
        run: |
          export CLANG_PATH=$HOME/clang
          export PATH="$CLANG_PATH/bin:$PATH"
          make O=out ARCH=arm64 defconfig
          make -j$(nproc) O=out \
            ARCH=arm64 \
            CC=clang \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_COMPAT=arm-linux-gnueabi-

      - name: Clone AnyKernel3
        run: |
          git clone --depth=1 https://github.com/osm0sis/AnyKernel3.git

      - name: Copy zImage to AnyKernel3
        run: |
          cp out/arch/arm64/boot/Image.gz AnyKernel3/

      - name: Zip Kernel
        run: |
          cd AnyKernel3
          zip -r9 PandoraKERNEL.zip ./*

      - name: Upload Flashable Zip
        uses: actions/upload-artifact@v4
        with:
          name: PandoraKERNEL_Flashable
          path: AnyKernel3/PandoraKERNEL.zip