name: Build PandoraKERNEL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt install -y \
          bc bison flex libssl-dev ccache build-essential \
          clang lld libncurses5-dev libncursesw5-dev git wget curl zip unzip python3

    - name: Clone AnyKernel3
      run: |
        git clone --depth=1 https://github.com/osm0sis/AnyKernel3.git

    - name: Build Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export KBUILD_BUILD_USER=PANđøʀᴀ
        export KBUILD_BUILD_HOST=GitHub-Actions

        mkdir -p out
        make O=out gki_defconfig
        make -j$(nproc) O=out \
          CC=clang \
          LD=ld.lld \
          CROSS_COMPILE=aarch64-linux-gnu- \
          CROSS_COMPILE_COMPAT=arm-linux-gnueabi-

    - name: Pack to AnyKernel
      run: |
        cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
        cd AnyKernel3
        zip -r9 PandoraKERNEL.zip *

    - name: Upload kernel zip
      uses: actions/upload-artifact@v4
      with:
        name: PandoraKERNEL
        path: AnyKernel3/PandoraKERNEL.zip
